Added option to uninstall

diff --git a/init.d/valkyrie_lcm_distro_bot_lcm_tunnel b/init.d/valkyrie_lcm_distro_bot_lcm_tunnel
--- a/init.d/valkyrie_lcm_distro_bot_lcm_tunnel
+++ b/init.d/valkyrie_lcm_distro_bot_lcm_tunnel
@@ -26,8 +26,7 @@ is_running() {
     [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
 }
 
-case "$1" in
-    start)
+start() {
     if is_running; then
         echo "Already started"
     else
@@ -44,8 +43,9 @@ case "$1" in
             exit 1
         fi
     fi
-    ;;
-    stop)
+}
+
+stop() {
     if is_running; then
         echo -n "Stopping $name.."
         kill `get_pid`
@@ -72,14 +72,39 @@ case "$1" in
     else
         echo "Not running"
     fi
-    ;;
-    restart)
+}
+
+restart() {
     $0 stop
     if is_running; then
         echo "Unable to stop, will not attempt to start"
         exit 1
     fi
     $0 start
+}
+
+uninstall() {
+  echo -n "Are you really sure you want to uninstall this service? This cannot be undone. [yes|no] "
+  local SURE
+  read SURE
+  if [ "$SURE" = "yes" ]; then
+    stop
+    rm -f "$pid_file"
+    echo "Notice: log files are not being removed" >&2
+    update-rc.d -f $name remove
+    rm -fv "$0"
+  fi
+}
+
+case "$1" in
+    start)
+    start
+    ;;
+    stop)
+    stop
+    ;;
+    restart)
+    restart
     ;;
     status)
     if is_running; then
@@ -88,6 +113,9 @@ case "$1" in
         echo "Stopped"
         exit 1
     fi
+    ;;
+    uninstall)
+    uninstall
     ;;
     *)
     echo "Usage: $0 {start|stop|restart|status}"
